name: Deploy to Beget

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: kalammcm.beget.tech
          username: kalammcm
          password: ${{ secrets.BEGET_FTP_PASSWORD }}
          server-dir: /tk-webb.ru/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            node_modules/**
            convert-webp.js
            package.json
            package-lock.json
